apiVersion: apps/v1
kind: Deployment
metadata:
  name: total-recall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: total-recall
  template:
    metadata:
      labels:
        app: total-recall
    spec:
      containers:
      - name: total-recall
        image: bkimminich/total-recall:latest
        ports:
        - containerPort: 3000
        securityContext:
          runAsUser: 0  # Running as root (vulnerability)
        resources: {}  # No resource limits set (vulnerability)
