server:
  port: 3000
  basePath: ''
  baseUrl: 'http://localhost:3000' # used for CSAF, e.g. https://example.com
application:
  domain: juice-sh.op # for pre-loaded email users
  name: 'Total Recall - Memory Vacations'
  logo: total-recall-brain-logo.png
  favicon: favicon_js.ico
  theme: bluegrey-lightgreen # Options: bluegrey-lightgreen blue-lightblue deeppurple-amber indigo-pink pink-bluegrey purple-green deeporange-indigo
  showVersionNumber: true
  showGitHubLinks: true
  localBackupEnabled: true
  numberOfRandomFakeUsers: 0
  altcoinName: Juicycoin
  privacyContactEmail: donotreply@owasp-juice.shop
  customMetricsPrefix: juiceshop
  chatBot:
    name: 'Juicy'
    greeting: "Nice to meet you <customer-name>, I'm <bot-name>"
    trainingData: 'botDefaultTrainingData.json'
    defaultResponse: "Sorry I couldn't understand what you were trying to say"
    avatar: 'JuicyChatBot.png'
  social:
    twitterUrl: 'https://twitter.com/owasp_juiceshop'
    facebookUrl: 'https://www.facebook.com/owasp.juiceshop'
    slackUrl: 'https://owasp.org/slack/invite'
    redditUrl: 'https://www.reddit.com/r/owasp_juiceshop'
    pressKitUrl: 'https://github.com/OWASP/owasp-swag/tree/master/projects/juice-shop'
    nftUrl: 'https://opensea.io/collection/juice-shop'
    questionnaireUrl: ~
  recyclePage:
    topProductImage: fruit_press.jpg
    bottomProductImage: apple_pressings.jpg
  welcomeBanner:
    showOnFirstStart: true
    title: 'Welcome to Total Recall - Memory Vacations!'
    message: "<p>Being a web application with a vast number of intended security vulnerabilities, the <strong>Total Recall - Memory Vacations</strong> is supposed to be the opposite of a best practice or template application for web developers: It is an awareness, training, demonstration and exercise tool for security risks in modern web applications. The <strong>Total Recall - Memory Vacations</strong> is an open-source project hosted by the non-profit <a href='https://owasp.org' target='_blank'>Open Worldwide Application Security Project (OWASP)</a> and is developed and maintained by volunteers. Check out the link below for more information and documentation on the project.</p><h1><a href='https://owasp-juice.shop' target='_blank'>https://owasp-juice.shop</a></h1>"
  cookieConsent:
    message: 'This website uses fruit cookies to ensure you get the juiciest tracking experience.'
    dismissText: 'Me want it!'
    linkText: 'But me wait!'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:donotreply@owasp-juice.shop'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
    hiring: '/#/jobs'
    csaf: '/.well-known/csaf/provider-metadata.json' # scheme,host,port taken from baseUrl
  promotion:
    video: owasp_promo.mp4
    subtitles: owasp_promo.vtt
  easterEggPlanet:
    name: Orangeuze
    overlayMap: orangemap2k.jpg
  googleOauth:
    clientId: '1005568560502-6hm16lef8oh46hr2d98vf2ohlnj4nfhq.apps.googleusercontent.com'
    authorizedRedirects:
      - { uri: 'https://demo.owasp-juice.shop' }
      - { uri: 'https://juice-shop.herokuapp.com' }
      - { uri: 'https://preview.owasp-juice.shop' }
      - { uri: 'https://juice-shop-staging.herokuapp.com' }
      - { uri: 'https://juice-shop.wtf' }
      - { uri: 'http://localhost:3000', proxy: 'https://local3000.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:3000', proxy: 'https://local3000.owasp-juice.shop' }
      - { uri: 'http://localhost:4200', proxy: 'https://local4200.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:4200', proxy: 'https://local4200.owasp-juice.shop' }
      - { uri: 'http://192.168.99.100:3000', proxy: 'https://localmac.owasp-juice.shop' }
      - { uri: 'http://192.168.99.100:4200', proxy: 'https://localmac.owasp-juice.shop' }
      - { uri: 'http://penguin.termina.linux.test:3000', proxy: 'https://localchromeos.owasp-juice.shop' }
      - { uri: 'http://penguin.termina.linux.test:4200', proxy: 'https://localchromeos.owasp-juice.shop' }
challenges:
  showSolvedNotifications: true
  showHints: true
  showMitigations: true
  codingChallengesEnabled: solved # Options: never  solved  always
  restrictToTutorialsFirst: false
  overwriteUrlForProductTamperingChallenge: 'https://owasp.slack.com'
  xssBonusPayload: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/771984076&color=%23ff5500&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  safetyMode: auto
  showFeedbackButtons: true
  csafHashValue: 7e7ce7c65db3bf0625fcea4573d25cff41f2f7e3474f2c74334b14fc65bb4fd26af802ad17a3a03bf0eee6827a00fb8f7905f338c31b5e6ea9cb31620242e843
hackingInstructor:
  isEnabled: true
  avatarImage: JuicyBot.png
  hintPlaybackSpeed: normal # Options: faster fast normal slow slower
products:
  -
    name: 'Pilot a Spaceship in the Andromeda Galaxy'
    description: ''
    price: 2.92
    quantity: 5
    limitPerUser: 5
    image: total-recall-pilot-a-spaceship.jpg
    useForChristmasSpecialChallenge: true
    reviews:
      - { text: 'text', author: rapper }
      - { text: 'text', author: jim }
  -
    name: 'Explore Mars'
    description: 'mbark on the ultimate adventure to the Red Planet, where the thrill of exploring Mars is just a memory away with Total Recalls immersive vacation experience.'
    price: 1.99
    image: total-recall-explore-mars.jpg
    urlForProductTamperingChallenge: 'https://www.owasp.org/index.php/O-Saft'
    reviews:
      - { text: 'Far out man!', author: jim }
  -
    name: 'Become a Covert Operative'
    description: 'text'
    price: 1.99
    image: total-recall-covert-ops.jpg
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
    exifForBlueprintChallenge:
      - OpenSCAD
    reviews:
      - { text: 'Far out man!', author: jim }
  -
    name: '1800s Steel Congolomerate Tycoon'
    description: 'text'
    price: 1.99
    image: total-recall-tycoon.jpg
    keywordsForPastebinDataLeakChallenge:
      - hueteroneel
      - eurogium edule
    reviews:
      - { text: 'Far out man!', author: jim }
  -
    name: 'Run the Maze as a Minotaur Huntress'
    description: 'text'
    price: 1.99
    image: total-recall-minotaur-hunter.jpg
    reviews:
      - { text: 'Far out man!', author: jim }
  -
    name: 'Be a Pharoah for a Week'
    description: 'text'
    price: 1.99
    image: total-recall-pharoah.jpg
    reviews:
      - { text: 'Far out man!', author: jim }
  -
    name: 'Serve as a 1980s Synthwave Detective'
    description: 'text'
    price: 1.99
    image: total-recall-80s-detective.jpg
    reviews:
      - { text: 'Far out man!', author: jim }
  -
    name: 'Be a Reclusive Botanist Stranded in a Carniverous Plant Jungle'
    description: 'text'
    price: 1.99
    image: total-recall-botanist.jpg
    reviews:
      - { text: 'Far out man!', author: jim }
memories:
  -
    image: 'magn(et)ificent!-1571814229653.jpg'
    caption: 'Magn(et)ificent!'
    user: bjoernGoogle
  -
    image: 'my-rare-collectors-item!-[Ã≤ÃÖ$Ã≤ÃÖ(Ã≤ÃÖ-Õ°¬∞-Õú ñ-Õ°¬∞Ã≤ÃÖ)Ã≤ÃÖ$Ã≤ÃÖ]-1572603645543.jpg'
    caption: 'My rare collectors item! [Ã≤ÃÖ$Ã≤ÃÖ(Ã≤ÃÖ Õ°¬∞ Õú ñ Õ°¬∞Ã≤ÃÖ)Ã≤ÃÖ$Ã≤ÃÖ]'
    user: bjoernGoogle
  -
    image: 'favorite-hiking-place.png'
    caption: 'I love going hiking here...'
    geoStalkingMetaSecurityQuestion: 14
    geoStalkingMetaSecurityAnswer: 'Daniel Boone National Forest'
  -
    image: 'IMG_4253.jpg'
    caption: 'My old workplace...'
    geoStalkingVisualSecurityQuestion: 10
    geoStalkingVisualSecurityAnswer: 'ITsec'
  -
    image: 'BeeHaven.png'
    caption: 'Welcome to the Bee Haven (/#/bee-haven)üêù'
    user: evm
  -
    image: 'sorted-the-pieces,-starting-assembly-process-1721152307290.jpg'
    caption: 'Sorted the pieces, starting assembly process...'
    user: bjoernOwasp
  -
    image: 'building-something-literally-bottom-up-1721152342603.jpg'
    caption: 'Building something literally bottom up...'
    user: bjoernOwasp
  -
    image: 'putting-in-the-hardware-1721152366854.jpg'
    caption: 'Putting in the hardware...'
    user: bjoernOwasp
  -
    image: 'everything-up-and-running!-1721152385146.jpg'
    caption: 'Everything up and running!'
    user: bjoernOwasp
ctf:
  showFlagsInNotifications: false
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
  countryMapping: ~
